### ISSUE TITLE
Unexpected close tag

### ISSUE THREAD

**Issue by nionis** [dfrankland/lastpass-node#2]
nodejs v6.6.0

Hey it seems that sometimes I randomly get errors even tho I am running the same code

``` node
Line: 6
Column: 63
Char: >
    at error (/mnt/d/work/lastpass-sshconfig/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/mnt/d/work/lastpass-sshconfig/node_modules/sax/lib/sax.js:693:7)
    at closeTag (/mnt/d/work/lastpass-sshconfig/node_modules/sax/lib/sax.js:887:9)
    at Object.write (/mnt/d/work/lastpass-sshconfig/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/mnt/d/work/lastpass-sshconfig/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/mnt/d/work/lastpass-sshconfig/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/mnt/d/work/lastpass-sshconfig/node_modules/xml2js/lib/xml2js.js:540:19)
    at tryCatcher (/mnt/d/work/lastpass-sshconfig/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/mnt/d/work/lastpass-sshconfig/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at /mnt/d/work/lastpass-sshconfig/node_modules/lastpass/dist/lib/getSession.js:63:24
    at next (native)
    at step (/mnt/d/work/lastpass-sshconfig/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /mnt/d/work/lastpass-sshconfig/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Here is the code

``` javascript
const lpass = require('lastpass').default,
  username = '***',
  password = '***'


const getAccounts = () =>
  user.getAccounts(username, password, {
    keyword: 'API 1'
  })

const user = new lpass()
const vault = user.loadVault(username, password)
  .then(getAccounts)
  .then(x => console.log(x))
  .catch(err => console.error(err))
}
```

**Comment by dfrankland** [comment]
The package throwing this error is [`sax`](https://www.npmjs.com/package/sax) and the reason it is throwing an error is because the response from Lastpass is probably invalid XML. What the reason is why it's intermittent is beyond me.

I recommend using the [`saveVaultFile`](https://github.com/dfrankland/lastpass-node#savevaultfilevaultfile-options) function if you can, that way you don't have to rely on Lastpass every time. If your passwords change often, that won't help obviously.

If you can, could you try logging what the response from Lastpass that can't be parsed by [`sax`](https://www.npmjs.com/package/sax) is?

**Comment by nionis** [comment]
I have run my script quite a few times and basically lastpass is blocking my IP because of its protection system, by using saveVaultFile I can mimize the requests, thank you!
